//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class author_menu_info
    {
        public int amno { get; set; }
        public string at_cd { get; set; }
        public string mn_cd { get; set; }
        public string mn_nm { get; set; }
        public string url_link { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string st_yn { get; set; }
        public string ct_yn { get; set; }
        public string mt_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
