//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class author_action
    {
        public int id { get; set; }
        public string mn_cd { get; set; }
        public string url_link { get; set; }
        public string id_button { get; set; }
        public string type { get; set; }
        public string name_table { get; set; }
        public string sts_action { get; set; }
        public string re_mark { get; set; }
    }
}
