//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyer_info
    {
        public int byno { get; set; }
        public string buyer_cd { get; set; }
        public string buyer_nm { get; set; }
        public string ceo_nm { get; set; }
        public string manager_nm { get; set; }
        public string brd_nm { get; set; }
        public string logo { get; set; }
        public string phone_nb { get; set; }
        public string cell_nb { get; set; }
        public string fax_nb { get; set; }
        public string e_mail { get; set; }
        public string address { get; set; }
        public string web_site { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public Nullable<int> stampId { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
