//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comm_dt
    {
        public int cdid { get; set; }
        public string mt_cd { get; set; }
        public string dt_cd { get; set; }
        public string dt_nm { get; set; }
        public string dt_kr { get; set; }
        public string dt_vn { get; set; }
        public string dt_exp { get; set; }
        public string up_cd { get; set; }
        public string val1 { get; set; }
        public string val1_nm { get; set; }
        public string val2 { get; set; }
        public string val2_nm { get; set; }
        public string val3 { get; set; }
        public string val3_nm { get; set; }
        public string val4 { get; set; }
        public string val4_nm { get; set; }
        public Nullable<int> dt_order { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
        public string unit { get; set; }
    }
}
