//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_bom_info
    {
        public int bid { get; set; }
        public string bom_no { get; set; }
        public string style_no { get; set; }
        public string mt_no { get; set; }
        public Nullable<double> need_time { get; set; }
        public Nullable<int> cav { get; set; }
        public Nullable<double> need_m { get; set; }
        public Nullable<double> buocdap { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
