//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_material_info
    {
        public int mtid { get; set; }
        public string mt_type { get; set; }
        public string mt_no { get; set; }
        public string mt_cd { get; set; }
        public string mt_no_origin { get; set; }
        public string mt_nm { get; set; }
        public string mf_cd { get; set; }
        public string gr_qty { get; set; }
        public string unit_cd { get; set; }
        public string bundle_qty { get; set; }
        public string bundle_unit { get; set; }
        public string sp_cd { get; set; }
        public string s_lot_no { get; set; }
        public string item_vcd { get; set; }
        public string qc_range_cd { get; set; }
        public string width { get; set; }
        public string width_unit { get; set; }
        public string spec { get; set; }
        public string spec_unit { get; set; }
        public string area { get; set; }
        public string area_unit { get; set; }
        public string thick { get; set; }
        public string thick_unit { get; set; }
        public string stick { get; set; }
        public string stick_unit { get; set; }
        public string consum_yn { get; set; }
        public string price { get; set; }
        public string tot_price { get; set; }
        public string price_unit { get; set; }
        public string price_least_unit { get; set; }
        public string photo_file { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string barcode { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
    }
}
