//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
          
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<author_action> author_action { get; set; }
        public DbSet<author_info> author_info { get; set; }
        public DbSet<author_menu_info> author_menu_info { get; set; }
        public DbSet<buyer_info> buyer_info { get; set; }
        public DbSet<comm_dt> comm_dt { get; set; }
        public DbSet<comm_mt> comm_mt { get; set; }
        public DbSet<d_bobbin_info> d_bobbin_info { get; set; }
        public DbSet<d_bobbin_lct_hist> d_bobbin_lct_hist { get; set; }
        public DbSet<d_bom_info> d_bom_info { get; set; }
        public DbSet<d_machine_info> d_machine_info { get; set; }
        public DbSet<d_material_info> d_material_info { get; set; }
        public DbSet<d_model_info> d_model_info { get; set; }
        public DbSet<d_mold_info> d_mold_info { get; set; }
        public DbSet<d_pro_unit_mc> d_pro_unit_mc { get; set; }
        public DbSet<d_pro_unit_staff> d_pro_unit_staff { get; set; }
        public DbSet<d_rounting_info> d_rounting_info { get; set; }
        public DbSet<d_style_info> d_style_info { get; set; }
        public DbSet<department_info> department_info { get; set; }
        public DbSet<generalfg> generalfgs { get; set; }
        public DbSet<history_container> history_container { get; set; }
        public DbSet<lct_info> lct_info { get; set; }
        public DbSet<m_board> m_board { get; set; }
        public DbSet<m_facline_qc> m_facline_qc { get; set; }
        public DbSet<m_facline_qc_value> m_facline_qc_value { get; set; }
        public DbSet<manufac_info> manufac_info { get; set; }
        public DbSet<mb_author_info> mb_author_info { get; set; }
        public DbSet<mb_info> mb_info { get; set; }
        public DbSet<mb_lct_info> mb_lct_info { get; set; }
        public DbSet<mb_message> mb_message { get; set; }
        public DbSet<menu_info> menu_info { get; set; }
        public DbSet<notice_board> notice_board { get; set; }
        public DbSet<qc_item_mt> qc_item_mt { get; set; }
        public DbSet<qc_itemcheck_dt> qc_itemcheck_dt { get; set; }
        public DbSet<qc_itemcheck_mt> qc_itemcheck_mt { get; set; }
        public DbSet<stamp_detail> stamp_detail { get; set; }
        public DbSet<stamp_master> stamp_master { get; set; }
        public DbSet<supplier_info> supplier_info { get; set; }
        public DbSet<user_author> user_author { get; set; }
        public DbSet<version_app> version_app { get; set; }
        public DbSet<w_actual> w_actual { get; set; }
        public DbSet<w_actual_primary> w_actual_primary { get; set; }
        public DbSet<w_box_mapping> w_box_mapping { get; set; }
        public DbSet<w_dl_info> w_dl_info { get; set; }
        public DbSet<w_ex_info> w_ex_info { get; set; }
        public DbSet<w_ext_info> w_ext_info { get; set; }
        public DbSet<w_material_down> w_material_down { get; set; }
        public DbSet<w_material_info> w_material_info { get; set; }
        public DbSet<w_material_info_memo> w_material_info_memo { get; set; }
        public DbSet<w_material_info_tam> w_material_info_tam { get; set; }
        public DbSet<w_material_mapping> w_material_mapping { get; set; }
        public DbSet<w_policy_mt> w_policy_mt { get; set; }
        public DbSet<w_product_qc> w_product_qc { get; set; }
        public DbSet<w_product_qc_value> w_product_qc_value { get; set; }
        public DbSet<w_rd_info> w_rd_info { get; set; }
        public DbSet<w_sd_info> w_sd_info { get; set; }
        public DbSet<w_vt_dt> w_vt_dt { get; set; }
        public DbSet<w_vt_mt> w_vt_mt { get; set; }
    }
}
