//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class department_info
    {
        public int dpno { get; set; }
        public string depart_cd { get; set; }
        public string depart_nm { get; set; }
        public string up_depart_cd { get; set; }
        public string level_cd { get; set; }
        public string re_mark { get; set; }
        public string use_yn { get; set; }
        public Nullable<int> order_no { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
        public string mn_full { get; set; }
    }
}
