//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class generalfg
    {
        public int id { get; set; }
        public string buyer_qr { get; set; }
        public string product_code { get; set; }
        public string md_cd { get; set; }
        public string dl_no { get; set; }
        public int qty { get; set; }
        public string type { get; set; }
        public string lot_no { get; set; }
        public string sts_cd { get; set; }
        public string use_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
