//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mb_message
    {
        public int tid { get; set; }
        public string message { get; set; }
        public string del_yn { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public string reg_id { get; set; }
    }
}
