//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notice_board
    {
        public int bno { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string mn_cd { get; set; }
        public Nullable<int> viewcnt { get; set; }
        public Nullable<int> replycnt { get; set; }
        public string div_cd { get; set; }
        public string lng_cd { get; set; }
        public string start_dt { get; set; }
        public string end_dt { get; set; }
        public Nullable<int> widthsize { get; set; }
        public Nullable<int> heightsize { get; set; }
        public string back_color { get; set; }
        public Nullable<int> order_no { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public string chg_id { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
    }
}
