//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stamp_detail
    {
        public int id { get; set; }
        public string buyer_qr { get; set; }
        public string stamp_code { get; set; }
        public string ssver { get; set; }
        public string product_code { get; set; }
        public string vendor_code { get; set; }
        public string vendor_line { get; set; }
        public string label_printer { get; set; }
        public string is_sample { get; set; }
        public string pcn { get; set; }
        public string lot_date { get; set; }
        public string serial_number { get; set; }
        public string machine_line { get; set; }
        public string shift { get; set; }
        public int standard_qty { get; set; }
        public string is_sent { get; set; }
        public string box_code { get; set; }
        public string reg_id { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public string chg_id { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
    }
}
