//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_author
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string at_nm { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
    }
}
