//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class version_app
    {
        public int id_app { get; set; }
        public string type { get; set; }
        public string name_file { get; set; }
        public int version { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
