//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_actual
    {
        public int id_actual { get; set; }
        public string at_no { get; set; }
        public string type { get; set; }
        public string product { get; set; }
        public Nullable<double> actual { get; set; }
        public Nullable<double> defect { get; set; }
        public string name { get; set; }
        public Nullable<int> level { get; set; }
        public string date { get; set; }
        public string don_vi_pr { get; set; }
        public string item_vcd { get; set; }
        public string description { get; set; }
        public bool IsFinished { get; set; }
        public string reg_id { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public string chg_id { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
    }
}
