//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_actual_primary
    {
        public int id_actualpr { get; set; }
        public string at_no { get; set; }
        public string type { get; set; }
        public Nullable<int> target { get; set; }
        public string product { get; set; }
        public string process_code { get; set; }
        public string remark { get; set; }
        public string finish_yn { get; set; }
        public string reg_id { get; set; }
        public Nullable<System.DateTime> reg_dt { get; set; }
        public string chg_id { get; set; }
        public Nullable<System.DateTime> chg_dt { get; set; }
    }
}
