//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_box_mapping
    {
        public int bmno { get; set; }
        public string bx_no { get; set; }
        public string buyer_cd { get; set; }
        public string mt_cd { get; set; }
        public int gr_qty { get; set; }
        public string product { get; set; }
        public string type { get; set; }
        public string mapping_dt { get; set; }
        public string sts { get; set; }
        public string use_yn { get; set; }
        public string del_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
