//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_ex_info
    {
        public int exid { get; set; }
        public string ex_no { get; set; }
        public string ex_nm { get; set; }
        public string ex_sts_cd { get; set; }
        public string work_dt { get; set; }
        public string lct_cd { get; set; }
        public Nullable<int> alert { get; set; }
        public string remark { get; set; }
        public string use_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
