//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_material_info_history
    {
        public int wmtid_his { get; set; }
        public string status { get; set; }
        public Nullable<int> wmtid { get; set; }
        public Nullable<int> id_actual { get; set; }
        public string at_no { get; set; }
        public string product { get; set; }
        public Nullable<int> id_actual_oqc { get; set; }
        public string staff_id { get; set; }
        public string staff_id_oqc { get; set; }
        public string machine_id { get; set; }
        public string mt_type { get; set; }
        public string mt_cd { get; set; }
        public string mt_no { get; set; }
        public Nullable<double> gr_qty { get; set; }
        public Nullable<double> real_qty { get; set; }
        public Nullable<int> staff_qty { get; set; }
        public string sp_cd { get; set; }
        public string rd_no { get; set; }
        public string sd_no { get; set; }
        public string ext_no { get; set; }
        public string ex_no { get; set; }
        public string dl_no { get; set; }
        public string recevice_dt { get; set; }
        public string date { get; set; }
        public string return_date { get; set; }
        public Nullable<int> alert_NG { get; set; }
        public string expiry_dt { get; set; }
        public string dt_of_receipt { get; set; }
        public string expore_dt { get; set; }
        public string recevice_dt_tims { get; set; }
        public Nullable<System.DateTime> end_production_dt { get; set; }
        public string lot_no { get; set; }
        public string mt_barcode { get; set; }
        public string mt_qrcode { get; set; }
        public string mt_sts_cd { get; set; }
        public string bb_no { get; set; }
        public string bbmp_sts_cd { get; set; }
        public string lct_cd { get; set; }
        public string lct_sts_cd { get; set; }
        public string from_lct_cd { get; set; }
        public string to_lct_cd { get; set; }
        public string output_dt { get; set; }
        public string input_dt { get; set; }
        public string buyer_qr { get; set; }
        public string orgin_mt_cd { get; set; }
        public string remark { get; set; }
        public string sts_update { get; set; }
        public string use_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
        public string date_insert { get; set; }
    }
}
