//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_material_info_memo
    {
        public int id { get; set; }
        public string md_cd { get; set; }
        public string style_no { get; set; }
        public string style_nm { get; set; }
        public string mt_cd { get; set; }
        public Nullable<decimal> width { get; set; }
        public string width_unit { get; set; }
        public Nullable<decimal> spec { get; set; }
        public string spec_unit { get; set; }
        public string sd_no { get; set; }
        public string lot_no { get; set; }
        public string sts_cd { get; set; }
        public string memo { get; set; }
        public string month_excel { get; set; }
        public string receiving_dt { get; set; }
        public Nullable<int> TX { get; set; }
        public Nullable<decimal> total_m { get; set; }
        public Nullable<decimal> total_m2 { get; set; }
        public Nullable<decimal> total_ea { get; set; }
        public string use_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
