//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_material_down
    {
        public int wmtid { get; set; }
        public string mt_cd { get; set; }
        public Nullable<double> gr_qty { get; set; }
        public Nullable<double> gr_down { get; set; }
        public string reason { get; set; }
        public string sts_now { get; set; }
        public string bb_no { get; set; }
        public string use_yn { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
