//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_policy_mt
    {
        public int wid { get; set; }
        public string policy_code { get; set; }
        public string policy_name { get; set; }
        public string policy_start_dt { get; set; }
        public string policy_end_dt { get; set; }
        public string work_starttime { get; set; }
        public string work_endtime { get; set; }
        public string lunch_start_time { get; set; }
        public string lunch_end_time { get; set; }
        public string dinner_start_time { get; set; }
        public string dinner_end_time { get; set; }
        public Nullable<decimal> work_hour { get; set; }
        public string use_yn { get; set; }
        public string last_yn { get; set; }
        public string re_mark { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
