//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class w_product_qc
    {
        public int pqno { get; set; }
        public string pq_no { get; set; }
        public string ml_no { get; set; }
        public string work_dt { get; set; }
        public string item_vcd { get; set; }
        public Nullable<int> check_qty { get; set; }
        public Nullable<int> ok_qty { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
