//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BomInfoModel
    {
        public int bid { get; set; }
        public string bom_no { get; set; }
        public string style_no { get; set; }
        public string mt_no { get; set; }
        public string mt_nm { get; set; }
        public float? need_time { get; set; }
        public int? cav { get; set; }
        public float? need_m { get; set; }
        public float? buocdap { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string md_cd { get; set; }
        public string style_nm { get; set; }
        public bool IsActive { get; set; }
        public string IsApply { get; set; }
    }
}
