//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRoutingInfo
    {
        public int idr { get; set; }
        public string style_no { get; set; }
        public string process_code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string isFinish { get; set; }
        public int? level { get; set; }
        public string don_vi_pr { get; set; }
        public string type { get; set; }
        public string item_vcd { get; set; }
        public string reg_id { get; set; }
        public DateTime? reg_dt { get; set; }
        public string chg_id { get; set; }
        public DateTime? chg_dt { get; set; }
    }
}
