//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductMaterailModel
    {
        public int id { get; set; }
        public string style_no { get; set; }
        public string process_code { get; set; }
        public int level { get; set; }
        public string mt_no { get; set; }
        public string name { get; set; }
        public string mt_nm { get; set; }
        public Nullable<double> need_time { get; set; }
        public Nullable<int> cav { get; set; }
        public Nullable<double> need_m { get; set; }
        public Nullable<double> buocdap { get; set; }
        public string isActive { get; set; }
        public string reg_id { get; set; }
        public System.DateTime reg_dt { get; set; }
        public string chg_id { get; set; }
        public System.DateTime chg_dt { get; set; }
    }
}
