//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_VD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMaterialTam
    {
        public int wmtid { get; set; }
        public string mt_cd { get; set; }
        public string mt_no { get; set; }
        public string gr_qty { get; set; }
        public string dt_of_receipt { get; set; }
        public string expiry_dt { get; set; }
        public string expore_dt { get; set; }
        public string lot_no { get; set; }
       
    }
}
